# Generated by Django 5.0.6 on 2024-05-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Randevular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('name_surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('personel', models.CharField(choices=[('EM', 'EMRAH'), ('LM', 'LOKMAN')], max_length=2)),
                ('saat', models.CharField(max_length=10)),
                ('note', models.TextField()),
                ('onay_durumu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Randevular',
                'verbose_name_plural': 'Randevular',
            },
        ),
    ]
