# Generated by Django 5.0.6 on 2024-05-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Personeller',
                'verbose_name_plural': 'Personeller',
            },
        ),
        migrations.CreateModel(
            name='Randevular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name_surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('hour', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('onay_durumu', models.BooleanField(default=False)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personeller')),
            ],
            options={
                'verbose_name': 'Randevular',
                'verbose_name_plural': 'Randevular',
            },
        ),
    ]
